language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python -m compileall ./index.py
  - python -m compileall ./data.py
  - python -m compileall ./cogs
  - python -m compileall ./util
  - python ./index.py
