language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python -m compileall ./index.py
  - python -m compileall ./data.py
  - python -m compileall ./cogs
  - python -m compileall ./util
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
